# Generated by Django 3.2.6 on 2021-08-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_remove_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
    ]
